### ISSUE TITLE
git忽略已经被提交的文件

### ISSUE THREAD

**Issue by koulerz** [zsqk/zsqk#30]
1. `git rm --cached [ File Path ]` 从 Git 的数据库中删除对于该文件的追踪 `git rm --cached` 删除的是追踪状态，而不是文件本身
2. 把对应的规则写入 .gitignore，让忽略真正生效
3. Commit + Push
## https://segmentfault.com/q/1010000000430426

忽略一个已经被跟踪的目录

```
$ git rm -r --cached dir
$ echo dir/ >> .gitignore
$ git add .gitignore
$ git commit -am 'ignore dir forever'
```

**Comment by iugo** [comment]
Git 默认是忽略大小写的. 以后如果想修改文件名的大小写, 就可能出现类似的问题, 需要用到上述信息.
