### ISSUE TITLE
antd Form 使用的 yiminghe/async-validator 存在一些问题

### ISSUE THREAD

**Issue by iugo** [zsqk/zsqk#57]
https://github.com/yiminghe/async-validator

async-validator 是阿里员工写的.

使用过程中, 发现目前 rules 存在一些问题.

1. type 的鸡肋. 对于 Form 而言, input 填充的都会是 string 类型, 此时 type rule 是无用的. 如果使用 transform 转化格式, 就失去了验证效果. 比如想要纯数字, 感觉 type rule int 类型是合适的, 但是实际上无法使用. 关于如何修改优化, 使用正则能解决. 类似问题: https://github.com/yiminghe/async-validator/issues/21

2. validator 的优化. 目前的格式为 function(rule, value, callback), 且 callback 必须被调用. 因为异步, 所以 callback 需要被调用是可以理解的, 可是这样写代码会难看一些. 优化为 function(value, rule) 需要 return 是合理的, 然后用 Promise 将 callback 这个显性的参数去除. 不过在我进一步看代码的时候, 发现如果要使用 Promise, 还是有比较大的工作量, 多处需要改动.

3. 自定义异步校验.

**Comment by ouzhou** [comment]
很尴尬的是今天写了一个验证端口号1-65535最后使用了pattern正则，或者使用validator callbacl在里面判断数字，但是最终的结果都是字符串，更尴尬的事情是填入的initialValue为一个数字是允许的。。
啥时候能用上内置的number啊？

**Comment by iugo** [comment]
@ouzhou 我们正在使用 antd. 表单验证的时候已经放弃和 antd 深度整合的 async-validator 了, antd
 允许自定义验证, 所以现在是自己直接操纵 form item 的一些属性控制验证. 尤其适合在一些异步验证, 混合数据验证的时候.
